#!/usr/bin/env python3
"""
gen_srt.py — Generate SRT subtitle file from voiceover_timing.json.

This fixes the subtitle/audio desync bug by using the EXACT audio timings
generated by gen_voiceover_timed.py, instead of estimated durations that drift.

Usage:
    python3 gen_srt.py <video_config.json> <output.srt> --timing voiceover_timing.json
"""
import json
import sys
import os
from datetime import timedelta

def fmt_time(t: float) -> str:
    td = timedelta(seconds=t)
    total_secs = int(td.total_seconds())
    h = total_secs // 3600
    m = (total_secs % 3600) // 60
    s = total_secs % 60
    ms = int(round((t - int(t)) * 1000))
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"

def main():
    config_path = sys.argv[1] if len(sys.argv) > 1 else "video_config.json"
    output_path = sys.argv[2] if len(sys.argv) > 2 else "timeline.srt"

    timing_path = None
    for i, arg in enumerate(sys.argv):
        if arg == "--timing" and i + 1 < len(sys.argv):
            timing_path = sys.argv[i + 1]

    if timing_path and os.path.exists(timing_path):
        print(f"  Generating SRT from exact timing file: {timing_path}")
        with open(timing_path) as f:
            timing_data = json.load(f)

        srt_parts = []
        for i, entry in enumerate(timing_data):
            t_start = entry["start"]
            t_end = entry["end"]
            text = entry["text"]
            srt_parts.append(f"{i + 1}\n{fmt_time(t_start)} --> {fmt_time(t_end)}\n{text}\n")

        with open(output_path, "w") as f:
            f.write("\n".join(srt_parts))
        print(f"Written: {output_path} ({len(timing_data)} entries, perfectly synced to audio)")
        return

    # Fallback to estimation without arbitrary scaling which caused the massive desync
    print("  WARNING: voiceover_timing.json not provided. Falling back to estimated duration (may drift).")
    with open(config_path) as f:
        cfg = json.load(f)

    voiceover_entries = cfg["audio"]["voiceover"]
    
    cumulative = 0.0
    srt_parts = []
    for i, vo in enumerate(voiceover_entries):
        dur = vo.get("durationSeconds", 1)
        t_start = cumulative
        t_end = t_start + dur
        cumulative += dur

        srt_parts.append(f"{i + 1}\n{fmt_time(t_start)} --> {fmt_time(t_end)}\n{vo['text']}\n")

    with open(output_path, "w") as f:
        f.write("\n".join(srt_parts))

    print(f"Written: {output_path} ({len(voiceover_entries)} entries)")

if __name__ == "__main__":
    main()
