export interface Theme {
  name: string;
  bg: string;
  text: string;
  accent: string;
  subtitle: string;
  divider: string;
  points: string;
  fontFamily: string;
  bullet: string;
  titleFontWeight: number;
  titleFontSize: number;
  titleLetterSpacing: number;

  // 装饰层（可选）
  vignette?: boolean;
  pattern?: "dot-grid" | "noise" | null;

  // 个性旋钮（可选）
  borderRadius?: number;
  ruleStyle?: "solid" | "dashed" | "double";
  fontWeightBody?: number;
}

export const themes: Theme[] = [
  {
    name: "dark-purple",
    bg: "linear-gradient(135deg, #0f0c29, #302b63, #24243e)",
    text: "#fff",
    accent: "#6c63ff",
    subtitle: "#b8b5d0",
    divider: "#6c63ff",
    points: "#d0cee0",
    fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
    bullet: "\u2726",
    titleFontWeight: 700,
    titleFontSize: 72,
    titleLetterSpacing: -1,
    vignette: true,
    borderRadius: 0,
    ruleStyle: "solid",
    fontWeightBody: 400,
  },
  {
    name: "light-teal",
    bg: "linear-gradient(135deg, #e0f7fa, #80deea, #26c6da)",
    text: "#1a237e",
    accent: "#00838f",
    subtitle: "#283593",
    divider: "#00838f",
    points: "#37474f",
    fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
    bullet: "\u25b8",
    titleFontWeight: 700,
    titleFontSize: 72,
    titleLetterSpacing: 0,
    vignette: false,
    borderRadius: 4,
    ruleStyle: "solid",
    fontWeightBody: 400,
  },
  {
    name: "warm-orange",
    bg: "linear-gradient(135deg, #ff6f00, #ff8f00, #ffb300)",
    text: "#fff",
    accent: "rgba(255,255,255,0.6)",
    subtitle: "#fff3e0",
    divider: "rgba(255,255,255,0.6)",
    points: "#fff8e1",
    fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
    bullet: "\u2605",
    titleFontWeight: 700,
    titleFontSize: 72,
    titleLetterSpacing: 0,
    pattern: "noise",
    borderRadius: 0,
    ruleStyle: "solid",
    fontWeightBody: 400,
  },
  {
    name: "dark-red",
    bg: "linear-gradient(135deg, #1a0000, #4a0000, #6b1a1a)",
    text: "#f5e6e6",
    accent: "#c62828",
    subtitle: "#d4a0a0",
    divider: "#c62828",
    points: "#e0c0c0",
    fontFamily: "'Playfair Display', 'Noto Sans SC', serif",
    bullet: "\u25c6",
    titleFontWeight: 700,
    titleFontSize: 72,
    titleLetterSpacing: 2,
    vignette: true,
    borderRadius: 2,
    ruleStyle: "double",
    fontWeightBody: 400,
  },
  {
    name: "glassmorphism",
    bg: "linear-gradient(135deg, #667eea, #764ba2)",
    text: "#fff",
    accent: "#a78bfa",
    subtitle: "#e0d4f0",
    divider: "#a78bfa",
    points: "#ddd6fe",
    fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
    bullet: "\u25cf",
    titleFontWeight: 700,
    titleFontSize: 72,
    titleLetterSpacing: 0,
    borderRadius: 8,
    ruleStyle: "solid",
    fontWeightBody: 400,
    vignette: true,
  },
  {
    name: "minimal-bw",
    bg: "#0a0a0a",
    text: "#fff",
    accent: "#444",
    subtitle: "#888",
    divider: "#444",
    points: "#ccc",
    fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
    bullet: "\u2014",
    titleFontWeight: 200,
    titleFontSize: 80,
    titleLetterSpacing: 4,
    pattern: "dot-grid",
    borderRadius: 0,
    ruleStyle: "solid",
    fontWeightBody: 300,
    vignette: true,
  },
  {
    name: "nature-green",
    bg: "linear-gradient(135deg, #1b5e20, #2e7d32, #43a047)",
    text: "#fff",
    accent: "#81c784",
    subtitle: "#c8e6c9",
    divider: "#81c784",
    points: "#e8f5e9",
    fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
    bullet: "\u2726",
    titleFontWeight: 700,
    titleFontSize: 72,
    titleLetterSpacing: 0,
    vignette: false,
    borderRadius: 2,
    ruleStyle: "solid",
    fontWeightBody: 400,
  },
  {
    name: "tech-grid",
    bg: "#0d1b2a",
    text: "#fff",
    accent: "#4169e1",
    subtitle: "#8892b0",
    divider: "#4169e1",
    points: "#a8b2d1",
    fontFamily: "'JetBrains Mono', 'Noto Sans SC', monospace",
    bullet: ">",
    titleFontWeight: 700,
    titleFontSize: 64,
    titleLetterSpacing: 0,
    pattern: "dot-grid",
    borderRadius: 0,
    ruleStyle: "solid",
    fontWeightBody: 400,
    vignette: true,
  },
  {
    name: "warm-yellow",
    bg: "linear-gradient(135deg, #f57f17, #f9a825, #fdd835)",
    text: "#1a1a1a",
    accent: "#bf360c",
    subtitle: "#3e2723",
    divider: "#bf360c",
    points: "#4e342e",
    fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
    bullet: "\u2b21",
    titleFontWeight: 800,
    titleFontSize: 76,
    titleLetterSpacing: 0,
    vignette: false,
    borderRadius: 2,
    ruleStyle: "solid",
    fontWeightBody: 400,
  },
  {
    name: "sakura-pink",
    bg: "linear-gradient(135deg, #fce4ec, #f8bbd0, #f48fb1)",
    text: "#4a1a2e",
    accent: "#d81b60",
    subtitle: "#6a1b3a",
    divider: "#d81b60",
    points: "#4a1a2e",
    fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
    bullet: "\u2726",
    titleFontWeight: 700,
    titleFontSize: 72,
    titleLetterSpacing: 0,
    vignette: false,
    borderRadius: 6,
    ruleStyle: "dashed",
    fontWeightBody: 400,
  },
  {
    name: "neon-blue",
    bg: "linear-gradient(135deg, #0a0020, #1a0050, #0d0030)",
    text: "#fff",
    accent: "#6464ff",
    subtitle: "#a0a0ff",
    divider: "#6464ff",
    points: "#c0c0ff",
    fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
    bullet: "\u26a1",
    titleFontWeight: 700,
    titleFontSize: 72,
    titleLetterSpacing: 0,
    vignette: true,
    borderRadius: 0,
    ruleStyle: "solid",
    fontWeightBody: 400,
  },
  {
    name: "matte-metal",
    bg: "linear-gradient(135deg, #263238, #37474f, #455a64)",
    text: "#eceff1",
    accent: "#78909c",
    subtitle: "#b0bec5",
    divider: "#78909c",
    points: "#cfd8dc",
    fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
    bullet: "\u25b9",
    titleFontWeight: 300,
    titleFontSize: 72,
    titleLetterSpacing: 3,
    pattern: "noise",
    borderRadius: 0,
    ruleStyle: "solid",
    fontWeightBody: 300,
    vignette: true,
  },
];
