import React from "react";
import { AbsoluteFill, Sequence } from "remotion";
import { IntroScene } from "./compositions/IntroScene";
import { OrganicBlob } from "./components/decoration/OrganicBlob";
import { ExperimentCardLight } from "./components/content/ExperimentCardLight";
import { FlowMusicCard } from "./components/content/FlowMusicCard";
import { CoverflowCarousel } from "./components/layout/CoverflowCarousel";
import { FilterPills } from "./components/content/FilterPills";

const Theme = { bg: "#F5F4F0", dark: "#202120", yellow: "#FFD54F", blue: "#4285F4", pink: "#F48FB1", green: "#34A853" };
const FPS = 24;
const WORDS = ["experiment", "create", "develop", "learn", "explore"];
const BLOB_COLORS = [Theme.blue, Theme.pink, Theme.dark, Theme.blue, Theme.yellow];
const CARDS = [
  { title: "Pomelli", description: "AI-powered marketing tool that crafts campaigns and analyzes performance.", imageColor: Theme.yellow, accentColor: "#E8A80C" },
  { title: "Project Genie", description: "Explore infinitely diverse worlds generated by your imagination.", imageColor: Theme.dark, accentColor: Theme.green },
  { title: "Stitch", description: "Transforms natural language into polished user interface designs instantly.", imageColor: Theme.pink, accentColor: "#E04070" },
  { title: "Labs Playground", description: "Experiment with cutting-edge AI tools before they launch to production.", imageColor: "#E8A87C", accentColor: "#C06030" },
];
const FILTERS = ["All", "Create", "Develop", "Learn", "Play"];

// ═══ Scene 2: Flash Text (5s) ═══
const FlashTextScene: React.FC = () => (
  <AbsoluteFill style={{ backgroundColor: Theme.bg, overflow: "hidden" }}>
    {WORDS.map((word, i) => (
      <Sequence key={word} from={i * FPS} durationInFrames={FPS}>
        <AbsoluteFill style={{ filter: "blur(40px)", opacity: 0.7 }}>
          <div style={{ position: "absolute", top: -150, left: -100 + i * 150 }}>
            <OrganicBlob color={BLOB_COLORS[i]} size={1000} delay={0} morphing />
          </div>
          <div style={{ position: "absolute", top: 200, right: -100 - i * 100 }}>
            <OrganicBlob color={BLOB_COLORS[(i + 1) % BLOB_COLORS.length]} size={700} delay={0} morphing />
          </div>
        </AbsoluteFill>
        <AbsoluteFill style={{ justifyContent: "center", alignItems: "center", zIndex: 10 }}>
          <div style={{
            fontFamily: "Inter, 'Google Sans', sans-serif", fontSize: 120, fontWeight: 700,
            textAlign: "center", lineHeight: 1.1, letterSpacing: "-0.03em",
            color: BLOB_COLORS[i] === Theme.dark ? "#FFF" : Theme.dark,
          }}>
            <div>Be the first to</div><div>{word}</div>
          </div>
        </AbsoluteFill>
      </Sequence>
    ))}
  </AbsoluteFill>
);

// ═══ Scene 5: Coverflow (7s) ═══
const CoverflowScene: React.FC = () => (
  <AbsoluteFill style={{ backgroundColor: Theme.bg }}>
    <div style={{ opacity: 0.25, filter: "blur(60px)" }}>
      <OrganicBlob color={Theme.blue} position="top-left" delay={0} size={600} morphing />
      <OrganicBlob color={Theme.pink} position="bottom-right" delay={0} size={500} morphing />
    </div>
    <div style={{ position: "absolute", top: 60, left: 0, right: 0, textAlign: "center", fontFamily: "Inter, sans-serif", fontSize: 36, fontWeight: 600, color: Theme.dark, letterSpacing: "-0.01em" }}>
      Explore our latest experiments
    </div>
    <CoverflowCarousel cardWidth={400} gap={60} scrollSpeed={55}>
      <FlowMusicCard />
      {CARDS.map((card, i) => <ExperimentCardLight key={i} {...card} />)}
    </CoverflowCarousel>
    <div style={{ position: "absolute", bottom: 60, left: 0, right: 0 }}>
      <FilterPills items={FILTERS} activeIndex={0} startFrame={40} />
    </div>
  </AbsoluteFill>
);

// ═══ Scene 6: CTA (4s) ═══
const GridScene: React.FC = () => (
  <AbsoluteFill style={{ backgroundColor: Theme.dark, justifyContent: "center", alignItems: "center", gap: 40 }}>
    <div style={{ fontFamily: "Inter, sans-serif", fontSize: 48, fontWeight: 700, color: "#FFF", textAlign: "center", letterSpacing: "-0.02em" }}>Start experimenting today</div>
    <div style={{ display: "flex", gap: 14, fontFamily: "Inter, sans-serif", fontSize: 16, fontWeight: 500 }}>
      {["Try Google Flow", "Explore Labs"].map((label, i) => (
        <div key={i} style={{ padding: "14px 32px", borderRadius: 999, background: i === 0 ? Theme.blue : "transparent", color: i === 0 ? "#FFF" : "rgba(255,255,255,0.7)", border: i === 0 ? "none" : "1px solid rgba(255,255,255,0.3)", cursor: "default" }}>{label}</div>
      ))}
    </div>
    <div style={{ position: "absolute", bottom: -200, right: -100, opacity: 0.3, filter: "blur(50px)" }}><OrganicBlob color={Theme.blue} size={500} morphing /></div>
    <div style={{ position: "absolute", top: -150, left: -100, opacity: 0.25, filter: "blur(50px)" }}><OrganicBlob color={Theme.pink} size={400} morphing /></div>
  </AbsoluteFill>
);

// ═══ Root: 4 scenes, 456f / 19s ═══
export const PlayfulShowcase: React.FC = () => (
  <>
    {/* S1: Intro (0-71, 3s) */}
    <Sequence from={0} durationInFrames={FPS * 3}><IntroScene /></Sequence>
    {/* S2: Flash Text (72-191, 5s) */}
    <Sequence from={FPS * 3} durationInFrames={FPS * 5}><FlashTextScene /></Sequence>
    {/* S3: Coverflow (192-359, 7s) */}
    <Sequence from={FPS * 8} durationInFrames={FPS * 7}><CoverflowScene /></Sequence>
    {/* S4: CTA (360-455, 4s) */}
    <Sequence from={FPS * 15} durationInFrames={FPS * 4}><GridScene /></Sequence>
  </>
);
