/**
 * styles.ts — 12 套样式模板。
 *
 * 从 themes.ts 迁移，增加 family 分类和结构化的 colors/typography/decoration。
 * 每个样式模板 = 色彩方案 + 字体方案 + 装饰系统 + 特殊效果。
 */
import { StyleTemplate } from "./types";

export const styleTemplates: StyleTemplate[] = [
  {
    id: "dark-purple",
    family: "tech",
    displayName: "Dark Purple",
    mood: ["dark", "tech", "professional"],
    colors: {
      background: "linear-gradient(135deg, #0f0c29, #302b63, #24243e)",
      surface: "#302b63",
      primary: "#6c63ff",
      accent: "#6c63ff",
      text: "#fff",
      textMuted: "#b8b5d0",
      divider: "#6c63ff",
    },
    typography: {
      fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
      titleWeight: 700,
      bodyWeight: 400,
      titleLetterSpacing: -1,
      titleSize: 72,
    },
    decoration: {
      vignette: true,
      pattern: null,
      borderRadius: 0,
      ruleStyle: "solid",
      bulletChar: "\u2726",
    },
    defaultBgType: "geometric",
  },
  {
    id: "light-teal",
    family: "business",
    displayName: "Light Teal",
    mood: ["light", "clean", "modern"],
    colors: {
      background: "linear-gradient(135deg, #e0f7fa, #80deea, #26c6da)",
      surface: "#80deea",
      primary: "#00838f",
      accent: "#00838f",
      text: "#1a237e",
      textMuted: "#283593",
      divider: "#00838f",
    },
    typography: {
      fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
      titleWeight: 700,
      bodyWeight: 400,
      titleLetterSpacing: 0,
      titleSize: 72,
    },
    decoration: {
      vignette: false,
      pattern: null,
      borderRadius: 4,
      ruleStyle: "solid",
      bulletChar: "\u25b8",
    },
    defaultBgType: "bokeh",
  },
  {
    id: "warm-orange",
    family: "playful",
    displayName: "Warm Orange",
    mood: ["warm", "energetic", "creative"],
    colors: {
      background: "linear-gradient(135deg, #ff6f00, #ff8f00, #ffb300)",
      surface: "#ff8f00",
      primary: "rgba(255,255,255,0.6)",
      accent: "rgba(255,255,255,0.6)",
      text: "#fff",
      textMuted: "#fff3e0",
      divider: "rgba(255,255,255,0.6)",
    },
    typography: {
      fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
      titleWeight: 700,
      bodyWeight: 400,
      titleLetterSpacing: 0,
      titleSize: 72,
    },
    decoration: {
      vignette: false,
      pattern: "noise",
      borderRadius: 0,
      ruleStyle: "solid",
      bulletChar: "\u2605",
    },
    defaultBgType: "pixel",
    effects: {
      shadowPreset: "warm",
    },
  },
  {
    id: "dark-red",
    family: "business",
    displayName: "Dark Red",
    mood: ["dark", "elegant", "serious"],
    colors: {
      background: "linear-gradient(135deg, #1a0000, #4a0000, #6b1a1a)",
      surface: "#4a0000",
      primary: "#c62828",
      accent: "#c62828",
      text: "#f5e6e6",
      textMuted: "#d4a0a0",
      divider: "#c62828",
    },
    typography: {
      fontFamily: "'Playfair Display', 'Noto Sans SC', serif",
      titleWeight: 700,
      bodyWeight: 400,
      titleLetterSpacing: 2,
      titleSize: 72,
    },
    decoration: {
      vignette: true,
      pattern: null,
      borderRadius: 2,
      ruleStyle: "double",
      bulletChar: "\u25c6",
    },
    defaultBgType: "starfield",
    effects: {
      italicForSubtitle: true,
    },
  },
  {
    id: "glassmorphism",
    family: "creative",
    displayName: "Glassmorphism",
    mood: ["modern", "glassy", "futuristic"],
    colors: {
      background: "linear-gradient(135deg, #667eea, #764ba2)",
      surface: "#764ba2",
      primary: "#a78bfa",
      accent: "#a78bfa",
      text: "#fff",
      textMuted: "#e0d4f0",
      divider: "#a78bfa",
    },
    typography: {
      fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
      titleWeight: 700,
      bodyWeight: 400,
      titleLetterSpacing: 0,
      titleSize: 72,
    },
    decoration: {
      vignette: true,
      pattern: null,
      borderRadius: 8,
      ruleStyle: "solid",
      bulletChar: "\u25cf",
    },
    defaultBgType: "bokeh",
  },
  {
    id: "minimal-bw",
    family: "minimal",
    displayName: "Minimal Black & White",
    mood: ["dark", "minimal", "stark"],
    colors: {
      background: "#0a0a0a",
      surface: "#111",
      primary: "#444",
      accent: "#444",
      text: "#fff",
      textMuted: "#888",
      divider: "#444",
    },
    typography: {
      fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
      titleWeight: 200,
      bodyWeight: 300,
      titleLetterSpacing: 4,
      titleSize: 80,
    },
    decoration: {
      vignette: true,
      pattern: "dot-grid",
      borderRadius: 0,
      ruleStyle: "solid",
      bulletChar: "\u2014",
      textTransform: "uppercase",
    },
    defaultBgType: "geometric",
  },
  {
    id: "nature-green",
    family: "business",
    displayName: "Nature Green",
    mood: ["warm", "natural", "calm"],
    colors: {
      background: "linear-gradient(135deg, #1b5e20, #2e7d32, #43a047)",
      surface: "#2e7d32",
      primary: "#81c784",
      accent: "#81c784",
      text: "#fff",
      textMuted: "#c8e6c9",
      divider: "#81c784",
    },
    typography: {
      fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
      titleWeight: 700,
      bodyWeight: 400,
      titleLetterSpacing: 0,
      titleSize: 72,
    },
    decoration: {
      vignette: false,
      pattern: null,
      borderRadius: 2,
      ruleStyle: "solid",
      bulletChar: "\u2726",
    },
    defaultBgType: "starfield",
  },
  {
    id: "tech-grid",
    family: "tech",
    displayName: "Tech Grid",
    mood: ["dark", "tech", "code", "data"],
    colors: {
      background: "#0d1b2a",
      surface: "#1b2838",
      primary: "#4169e1",
      accent: "#4169e1",
      text: "#fff",
      textMuted: "#8892b0",
      divider: "#4169e1",
    },
    typography: {
      fontFamily: "'JetBrains Mono', 'Noto Sans SC', monospace",
      titleWeight: 700,
      bodyWeight: 400,
      titleLetterSpacing: 0,
      titleSize: 64,
    },
    decoration: {
      vignette: true,
      pattern: "dot-grid",
      borderRadius: 0,
      ruleStyle: "solid",
      bulletChar: ">",
    },
    defaultBgType: "geometric",
  },
  {
    id: "warm-yellow",
    family: "playful",
    displayName: "Warm Yellow",
    mood: ["warm", "sunny", "energetic"],
    colors: {
      background: "linear-gradient(135deg, #f57f17, #f9a825, #fdd835)",
      surface: "#f9a825",
      primary: "#bf360c",
      accent: "#bf360c",
      text: "#1a1a1a",
      textMuted: "#3e2723",
      divider: "#bf360c",
    },
    typography: {
      fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
      titleWeight: 800,
      bodyWeight: 400,
      titleLetterSpacing: 0,
      titleSize: 76,
    },
    decoration: {
      vignette: false,
      pattern: null,
      borderRadius: 2,
      ruleStyle: "solid",
      bulletChar: "\u2b21",
    },
    defaultBgType: "pixel",
  },
  {
    id: "sakura-pink",
    family: "creative",
    displayName: "Sakura Pink",
    mood: ["light", "warm", "design"],
    colors: {
      background: "linear-gradient(135deg, #fce4ec, #f8bbd0, #f48fb1)",
      surface: "#f8bbd0",
      primary: "#d81b60",
      accent: "#d81b60",
      text: "#4a1a2e",
      textMuted: "#6a1b3a",
      divider: "#d81b60",
    },
    typography: {
      fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
      titleWeight: 700,
      bodyWeight: 400,
      titleLetterSpacing: 0,
      titleSize: 72,
    },
    decoration: {
      vignette: false,
      pattern: null,
      borderRadius: 6,
      ruleStyle: "dashed",
      bulletChar: "\u2726",
    },
    defaultBgType: "bokeh",
  },
  {
    id: "neon-blue",
    family: "tech",
    displayName: "Neon Blue",
    mood: ["dark", "cyber", "gaming"],
    colors: {
      background: "linear-gradient(135deg, #0a0020, #1a0050, #0d0030)",
      surface: "#1a0050",
      primary: "#6464ff",
      accent: "#6464ff",
      text: "#fff",
      textMuted: "#a0a0ff",
      divider: "#6464ff",
    },
    typography: {
      fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
      titleWeight: 700,
      bodyWeight: 400,
      titleLetterSpacing: 0,
      titleSize: 72,
    },
    decoration: {
      vignette: true,
      pattern: null,
      borderRadius: 0,
      ruleStyle: "solid",
      bulletChar: "\u26a1",
    },
    defaultBgType: "pixel",
    effects: {
      glowColor: "rgba(100,100,255,0.8)",
      shadowPreset: "neon",
    },
  },
  {
    id: "matte-metal",
    family: "minimal",
    displayName: "Matte Metal",
    mood: ["dark", "industrial", "cold"],
    colors: {
      background: "linear-gradient(135deg, #263238, #37474f, #455a64)",
      surface: "#37474f",
      primary: "#78909c",
      accent: "#78909c",
      text: "#eceff1",
      textMuted: "#b0bec5",
      divider: "#78909c",
    },
    typography: {
      fontFamily: "'Inter', 'Noto Sans SC', sans-serif",
      titleWeight: 300,
      bodyWeight: 300,
      titleLetterSpacing: 3,
      titleSize: 72,
    },
    decoration: {
      vignette: true,
      pattern: "noise",
      borderRadius: 0,
      ruleStyle: "solid",
      bulletChar: "\u25b9",
      textTransform: "uppercase",
    },
    defaultBgType: "starfield",
  },
];
